### ISSUE TITLE
Visual Studio SSH debugger issue

### ISSUE THREAD

**Issue by annymsMthd** [xamarin/xamarin-iot-samples#1]
Where would I go to look at the code for the visual studio plugin / or post an issue for it?

**Comment by netonjm** [comment]
Hello! The addin is a part of the Xamarin toolkit there is no source code available. At the moment we are in preview stage and there is no official issue system. But like a Xamarin Studio addin you can post your problem in our forums... 
mac: https://forums.xamarin.com/categories/xamarin-studio
windows: https://forums.xamarin.com/categories/visual-studio

We'll change this in a near the future!
Thanks for your message!

**Comment by netonjm** [comment]
Now we have a bugzilla thread!
https://bugzilla.xamarin.com/describecomponents.cgi?product=IoT
